### ISSUE TITLE
Enable paket bootstrapping through msbuild

### ISSUE THREAD

**Issue by eiriktsarpalis** [elastacloud/mbrace-on-brisk-starter#32]
I see that the current version of the solution bootstraps paket using a batch file at the root directory and think that this may be confusing to some people. What if we incorporated paket.targets in the Demos project so that packages can by restored by simply building the solution?

**Comment by isaacabraham** [comment]
Yes, good idea. I'm out today so if you want to do that today go ahead, no objections, otherwise I'll do it tomorrow.

**Comment by isaacabraham** [comment]
Closed through 70689b1

**Comment by eiriktsarpalis** [comment]
The demo project needs to be enabled at build configuration, otherwise the paket target will not be run.

**Comment by isaacabraham** [comment]
It should be - just doing a build of the project should do the trick?

**Comment by eiriktsarpalis** [comment]
True, I was trying a solution-wide build

**Comment by isaacabraham** [comment]
Hmmm. But if you fell foul of that, other people will as well. Not sure how to get around that except through documentation?

**Comment by eiriktsarpalis** [comment]
We just need to re-tick this:
![enable](https://cloud.githubusercontent.com/assets/2813363/6443519/13189416-c100-11e4-88a4-4f5691423f1d.png)

**Comment by isaacabraham** [comment]
Ah ok.
