### ISSUE TITLE
Leaked connection strings in credentials.fsx

### ISSUE THREAD

**Issue by eiriktsarpalis** [elastacloud/mbrace-on-brisk-starter#33]
They should probably be removed and keys should be revoked /cc @dsyme

**Comment by isaacabraham** [comment]
I think they've already been revoked, but yes, should be removed as well and reverted to the blank string. Perhaps add the file to git.ignore?

**Comment by eiriktsarpalis** [comment]
Yes, possibly.

**Comment by dsyme** [comment]
I've revoked the credentials, thanks
