### ISSUE TITLE
Add tutorial on auto-scaling 

### ISSUE THREAD

**Issue by dsyme** [elastacloud/mbrace-on-brisk-starter#35]
I’ve been playing around with changing the cluster size while processing CPU-intensive jobs.  Some notes are below.

I recommend we add a tutorial on the Azure cluster size and auto-scaling options to the Brisk getting-started information.
- _Changing cluster size_.  I used the Azure portal to change the cluster size while processing CPU-intensive jobs.  No problems so far, the services seem to be able to transition well.    (Though I'm still waiting to see if jobs that were aborted due to a down-scaling transition are correctly restarted when using the fault-tolerance default settings)
- _Auto-scale by CPU_. I checked out Azure Cloud Service CPU auto-scaling for Brisk+MBrace. It works well enough.  The auto-scale is not super-fast  (Azure measures the service over an hour, then scales up if it’s been high CPU) but it at least give some degree of elasticity.
- _Auto-scale by queue length_.  I haven't played with this yet. You can also auto-scale w.r.t. queue length which seems like it would work reasonably well for MBrace, given the MBrace work queue is used to mediate work in general. The defaults make transitions when there are ~2000 entries in the queue - for mbrace this would probably be more like 2-10 depending on granularities, since work feels like it will be much chunkier.
- _Transitions and fault-tolerance_.  Either way, information on how the transitions are performed would be useful. Will a worker be brought down hard mid-computation? This is related to having a decent tutorial on fault-tolerance #34 )

I think it would be worth documenting the status of these options in the starter pack. It seems manually adjusting the cluster size up to 10 is a great way to experiment with a larger cluster, and automatic auto-scaling down to 1 worker is a great way to reduce costs when experimenting on and off.

Annoyingly the azure portal doesn't seem to remember your auto-scaling options as you switch auto-scaling on and off.  I assume that these can be set via a management API as well.

**Comment by dsyme** [comment]
FWIW, when I scaled the cluster down, a bunch of jobs were left running and look as if they will never fault nor complete. The jobs are 2 minutes long. The default FaultPolicy is InfiniteRetry, so my understanding is that these should have faulted or completed by this time, so this feels like a bug to me.

[ Updated: I tried this again with a different set of processes, and the jobs that were left running during the downscale seem to have successfully restarted and completed (though no specific jobs were shown as "Faulted") ]

```
   2e689cabf89e4a10bb788d1f4121b812    Running  False      00:20:32.3309197    1 /   0 /   0 /   1  unit         02/03/2015 12:38:36 +00:00  N/A                        
   81ce49aef9894a01ac348a6384d24c51    Running  False      00:20:30.0509516    1 /   0 /   0 /   1  unit         02/03/2015 12:38:38 +00:00  N/A                        
  d11dde91afd546c48f3bd829c58f099b    Running  False      00:20:26.0954216    1 /   0 /   0 /   1  unit         02/03/2015 12:38:42 +00:00  N/A                        
   833585c21de7468d8c145a6f870c03a2    Running  False      00:20:14.4214531    1 /   0 /   0 /   1  unit         02/03/2015 12:38:54 +00:00  N/A                        
   6f0d8aebf5524c69bdd242a04e3d7824    Running  False      00:20:13.4124494    1 /   0 /   0 /   1  unit         02/03/2015 12:38:55 +00:00  N/A                        
   0c22d03c2a6c496690081e9c3de56dfe    Running  False      00:20:11.1984491    1 /   0 /   0 /   1  unit         02/03/2015 12:38:57 +00:00  N/A                        
   50d3de78aeb840f7876a419cc480d437    Running  False      00:20:09.0156686    1 /   0 /   0 /   1  unit         02/03/2015 12:38:59 +00:00  N/A                        
   30868dc85d88469d89729d354a8c5447    Running  False      00:20:06.1830356    1 /   0 /   0 /   1  unit         02/03/2015 12:39:02 +00:00  N/A                        
```

**Comment by isaacabraham** [comment]
Yeah, the Azure auto-scaler has no knowledge of what's happening when it decides to downscale, and you have no way of knowing node will be downscaled. So if you're running jobs that last 60 minutes each (for whatever reason!) then you could theoretically lose 59 minutes of work. If you have more finely-gained jobs it's obviously not such an issue,

**Comment by dsyme** [comment]
Moved to https://github.com/mbraceproject/MBrace.StarterKit/issues/9
