### ISSUE TITLE
Question, can't run any job in new brisk

### ISSUE THREAD

**Issue by lenadroid** [elastacloud/mbrace-on-brisk-starter#36]
I have existing brisk cluster created several weeks ago, have successfully used the examples the brisk-on-mbrace-starter solution with mbrace 0.5.\* version. However, when I try to run the new, updated solution - I cannot start any job. For example:
1. Successfully create the cluster / runtime object for my credentials

```
namespace FSI_0002
  val myStorageConnectionString : string
  val myServiceBusConnectionString : string
  val createStorageConnectionString :
    storageName:string * storageAccessKey:string -> string
  val createServiceBusConnectionString :
    serviceBusName:string * serviceBusKey:string -> string
  val config : MBrace.Azure.Runtime.Configuration

Binding session to 'D:\Brisk\mbrace-on-brisk-starter\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.Edm.dll'...
Binding session to 'D:\Brisk\mbrace-on-brisk-starter\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.Services.Client.dll'...
Binding session to 'D:\Brisk\mbrace-on-brisk-starter\src\Demos\../../packages/MBrace.Azure.Client/tools\Microsoft.Data.OData.dll'...
Binding session to 'D:\Brisk\mbrace-on-brisk-starter\src\Demos\../../packages/MBrace.Azure.Client/tools\Newtonsoft.Json.dll'...

val cluster : MBrace.Azure.Client.Runtime
```

2 . Try to run the following: 

```
let quickText = cloud { return "Hello world!" } |> cluster.Run
```

Here the F# interactive hangs
1. Reset F# interactive after some time and check the status of created job:

```
 aefa922cb6ab462986f0e81271361ae0     Posted  False      00:41:19.0257922    0 /   0 /   0 /   1 string  02.03.2015 12:42:09 +00:00  N/A            
```

So it is in "posted" state, and execution time for hello world is "00:41:19.0257922".

Will be thankful for any thoughts. Is it Brisk or MBrace issue?

**Comment by dsyme** [comment]
I'd suggest recreating the cluster from the brisk elastacloud service, even with new storage and servicebus.  The cluster software has been updated since then - there not yet a smooth upgrade path though that's under discussion

The latest software has a cluster.Reset() that resets everything (pretty well, from what I've seen so far)

**Comment by lenadroid** [comment]
@dsyme actually yes, that worked, hope we will need less cluster recreations in future :) Brisk saves much time when it comes to cluster infrastructure creation.

**Comment by isaacabraham** [comment]
@lenadroid I see this when I was trying to use the latest client-side API with an old cluster (or vice versa). Currently MBrace doesn't do too much in the way of version checking between client and server - this is something that will not doubt be added in the future.
