### ISSUE TITLE
Move to MBrace.Demos?

### ISSUE THREAD

**Issue by eiriktsarpalis** [elastacloud/mbrace-on-brisk-starter#44]
I was wondering if we could move this repo to [MBrace.Demos](https://github.com/mbraceproject/MBrace.Demos). We could maintain this as the authoritative collection of tutorials and library implementations.

**Comment by dsyme** [comment]
I think it would be MBrace.Azure.Demos (one of the advantages is that it can document/teach MBrace from the perspective of the Azure user).

**Comment by dsyme** [comment]
OK, I see, there is a directory for Azure in MBrace.Demos

**Comment by isaacabraham** [comment]
No objections (that I can think of at the moment!) :-)

**Comment by dsyme** [comment]
Could we rename MBrace.Demos to MBrace.StarterKits?

**Comment by dsyme** [comment]
I like the idea of there being a specific starter kit for MBrace + Azure, even if it is alongside other start kits which deal with other MBrace topics.

**Comment by eiriktsarpalis** [comment]
Given that MBrace.Azure is the only available implementation, I see no reason why there should be a distinction at this stage. That said, most examples should work in any runtime implementation. So we could initialise the `cluster` object at `credentials.fsx`, then have the samples consume it in a cluster-agnostic way.

**Comment by eiriktsarpalis** [comment]
I just moved all the demos to [MBrace.StarterKits](https://github.com/mbraceproject/MBrace.StarterKits) (formerly MBrace.Demos). I propose we should move to that repo.
